// Code generated by openapi-cli-generator. DO NOT EDIT.
// See https://github.com/danielgtaylor/openapi-cli-generator

package main

import (
	
	
	

	"github.com/danielgtaylor/openapi-cli-generator/cli"
	"github.com/pkg/errors"
	"github.com/rs/zerolog/log"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"gopkg.in/h2non/gentleman.v2"
)







var rosetta.JsonSubcommand bool

func rosetta.JsonServers() []map[string]string {
	return []map[string]string{
		
	}
}





func rosetta.JsonRegister(subcommand bool) {
	root := cli.Root

	if subcommand {
		root = &cobra.Command{
			Use: "rosetta.json",
			Short: "",
			Long: cli.Markdown("Build Once. Integrate Your Blockchain Everywhere.\n"),
		}
		rosetta.JsonSubcommand = true
	} else {
		cli.Root.Short = ""
		cli.Root.Long = cli.Markdown("Build Once. Integrate Your Blockchain Everywhere.\n")
	}

	

	
}
